### ISSUE TITLE
Uninstalling a plugin does not flush the in-memory configuration

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#533]
Uninstalling a plugin and reinstalling a plugin doesn't actually refresh the `config.yml`.

Repro:
1. Install Vectr plugin
2. make changes to the config.yml
3. Delete plugin
4. Reinstall plugin

The config.yml will contain the changes from before the delete action

**Comment by privateducky** [comment]
We'll aim to fix this for 1.7.

**Comment by makk94** [comment]
I can't repro this (in either prod or locally)

**Comment by makk94** [comment]
Likely this was a problem fixed by https://github.com/preludeorg/professional/commit/8ddac26ba2d461232da8b5ad8222d3b9dc8ed06d (which was submitted a day before you posted this issue)

**Comment by privateducky** [comment]
perfect. labeling as fixed in 1.7.

**Comment by jtothef** [comment]
This issue appears to still persist for me in 1.7

Running Operator on Windows 10.

1) Turn off Vectr plugin - > config.yml file is removed 
2) Turn on Vectr plugin -> config.yml is restored with old settings
3) Edit config.yml with new settings - > Operator does not appear to update Vectr
4) Turn off and on Vectr plugin - > config.yml is restored with old settings


From audit.log

`2022-07-28T16:01:07.286Z [INFO] {"fs-write":"C:\\Users\\me\\AppData\\Roaming\\Operator\\portal.prelude.org\\plugins\\Vectr\\Vectr.js"}
2022-07-28T16:01:07.287Z [INFO] {"fs-write":"C:\\Users\\me\\AppData\\Roaming\\Operator\\portal.prelude.org\\plugins\\Vectr\\config.yml"}
2022-07-28T16:01:07.284Z [ERROR] 404: https://portal.prelude.org/outpost/plugin/Vectr?`

**Comment by privateducky** [comment]
@makk94 can you investigate?

**Comment by makk94** [comment]
The behavior of "Turn off and on Vectr plugin - > config.yml is restored with old settings" sounds like the right/normal behavior to me. Did that used to be the way to get config changes picked up? I don't see that written on doc.prelude.org

Solutions:
So we don't currently watch the config.yml for changes right now, so they aren't picked up immediately

We have a periodic sync every hour that pick up any config changes. You can also refresh the Operator UI to pick up the config changes. 

I think refreshing the UI seems like an easy enough/ correct solution. If it isn't, or if we have a lot of non-UI users, we can also set up a watch on the config.yml file and use a callback to pick up the changes more immediately @privateducky
